# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Alwatr Containers

on:
  workflow_dispatch:

  push:
    branches:
      - ws/*

  pull_request:
    paths:
      - 'cloud/Dockerfile'
      - '.github/workflows/publish-alwatr-container.yml'

env:
  REGISTRY: ghcr.io
  USERNAME: ${{github.repository_owner}}
  # USERNAME: ${{github.actor}}
  # USERNAME: Alwatr

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - image: 12fy-ws
            description: Alwatr 12fy website.
            siteUrl: https://12fy.alwatr.ir
            # NGINX_FORCE_DOMAIN: 12fy.alwatr.ir
            # NGINX_FORCE_DOMAIN_STATUS: 302
            noIndex: 1

          - image: 12fy-ws-beta
            description: Alwatr 12fy beta website.
            siteUrl: https://beta.12fy.alwatr.ir
            # NGINX_FORCE_DOMAIN: beta.12fy.alwatr.ir
            # NGINX_FORCE_DOMAIN_STATUS: 302
            noIndex: 1

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v3.6.0

      - name: 🏗 Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: 🏗 Log into registry ${{ env.REGISTRY }}
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗 Extract metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          images: name=${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ matrix.image }},enable=true

          labels: |
            org.opencontainers.image.authors=Ali.Mihandoost@gmail.com
            org.opencontainers.image.title=@alwatr/${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.description }}

          tags: |
            type=semver,enable=true,pattern={{major}}
            type=semver,enable=true,pattern={{major}}.{{minor}}
            type=semver,enable=true,pattern={{version}}
            type=ref,enable=true,event=branch

      - name: 🚀 Build and push container image
        id: build-and-push
        uses: docker/build-push-action@v4.1.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: cloud/Dockerfile
          build-args: |
            siteUrl=${{ matrix.siteUrl }}
            noIndex=${{ matrix.noIndex }}
            NGINX_FORCE_DOMAIN=${{ matrix.NGINX_FORCE_DOMAIN }}
            NGINX_FORCE_DOMAIN_STATUS=${{ matrix.NGINX_FORCE_DOMAIN_STATUS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🏗 Install cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@v3.1.2

      - name: 🏗 Sign the published container image
        if: ${{github.event_name != 'pull_request'}}
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: echo "${{steps.meta.outputs.tags}}" | xargs -I {} cosign sign --yes {}@${{steps.build-and-push.outputs.digest}}
