# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Stale

on:
  workflow_dispatch:
  schedule:
    - cron: '2 8 * * *'

jobs:
  stale:
    name: Clean up stale issues and PRs
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: 🧹 Clean up stale issues and PRs
        uses: actions/stale@v8.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          remove-stale-when-updated: true
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: 'no-stale,help-wanted,good first issue'
          exempt-pr-labels: no-stale
          close-issue-label: auto-closed
          close-pr-label: auto-closed
          stale-issue-message: >
            There hasn't been any activity on this issue recently, and in order
            to prioritize active issues, it will be marked as stale.

            Please make sure to update to the latest version and
            check if that solves the issue. Let us know if that works for you
            by leaving a 👍

            Because this issue is marked as stale, it will be closed and locked
            in 7 days if no further activity occurs.

            Thank you for your contributions!
          stale-pr-message: >
            There hasn't been any activity on this pull request recently, and in
            order to prioritize active work, it has been marked as stale.

            This PR will be closed and locked in 7 days if no further activity
            occurs.

            Thank you for your contributions!
